/******************************************************************************
* Copyright (c) 2013 - 2014, AllSeen Alliance. All rights reserved.
*
*    Permission to use, copy, modify, and/or distribute this software for any
*    purpose with or without fee is hereby granted, provided that the above
*    copyright notice and this permission notice appear in all copies.
*
*    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
*    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
*    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
*    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
*    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
*    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
*    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
******************************************************************************/

#ifndef CONTROL_GENERATED_H_
#define CONTROL_GENERATED_H_

//#include <alljoyn.h>
//#include <alljoyn/controlpanel/Widgets/ActionWidget.h>
//#include <alljoyn/controlpanel/Widgets/PropertyWidget.h>
//#include <alljoyn/controlpanel/Widgets/ContainerWidget.h>
//#include <alljoyn/controlpanel/Widgets/LabelWidget.h>
//#include <alljoyn/controlpanel/Widgets/DialogWidget.h>
//#include <alljoyn/controlpanel/Common/HttpControl.h>
//#include <alljoyn/services_common/Services_Common.h>

#include <alljoyn.h>
#include <ActionWidget.h>
#include <PropertyWidget.h>
#include <ContainerWidget.h>
#include <LabelWidget.h>
#include <DialogWidget.h>
#include <HttpControl.h>
#include <Services_Common.h>


/**
* Defines and objectPaths
*/
#define NUM_PRECEDING_OBJECTS NUM_PRE_CONTROLPANEL_OBJECTS

#define GET_WIDGET_VALUE_CASES \
case EN_FURNITURE_FURNITURECONTROLLER_GET_VALUE: \
case EN_FURNITURE_ELECTRIC_FAN_GET_VALUE: \
case EN_FURNITURE_LED_GET_VALUE: \
case EN_FURNITURE_START_GET_VALUE: \
case EN_FURNITURE_STOP_GET_VALUE: \
case EN_FURNITURE_LAMP_GET_VALUE: \
case EN_FURNITURE_LIGHTCONFIRM_GET_VALUE: \
case EN_FURNITURE_CURRENTTEMP_GET_VALUE: \
case EN_FURNITURE_MODESTRINGPROPERTY_GET_VALUE: \
case EN_FURNITURE_CHECKBOXPROPERTY_GET_VALUE: \
case EN_FURNITURE_STARTDATEPROPERTY_GET_VALUE: \
case EN_FURNITURE_STARTTIMEPROPERTY_GET_VALUE: \


#define GET_WIDGET_ALL_VALUE_CASES \
case EN_FURNITURE_FURNITURECONTROLLER_GET_ALL_VALUES: \
case EN_FURNITURE_ELECTRIC_FAN_GET_ALL_VALUES: \
case EN_FURNITURE_LED_GET_ALL_VALUES: \
case EN_FURNITURE_START_GET_ALL_VALUES: \
case EN_FURNITURE_STOP_GET_ALL_VALUES: \
case EN_FURNITURE_LAMP_GET_ALL_VALUES: \
case EN_FURNITURE_LIGHTCONFIRM_GET_ALL_VALUES: \
case EN_FURNITURE_CURRENTTEMP_GET_ALL_VALUES: \
case EN_FURNITURE_MODESTRINGPROPERTY_GET_ALL_VALUES: \
case EN_FURNITURE_CHECKBOXPROPERTY_GET_ALL_VALUES: \
case EN_FURNITURE_STARTDATEPROPERTY_GET_ALL_VALUES: \
case EN_FURNITURE_STARTTIMEPROPERTY_GET_ALL_VALUES: \


#define GET_ROOT_VALUE_CASES \
case FURNITURE_HTTPCONTROL_GET_VALUE:\
case FURNITURE_ROOT_CONTROLPANEL_FURNITURECONTROLLER_GET_VALUE: \


#define GET_ROOT_ALL_VALUE_CASES \
case FURNITURE_HTTPCONTROL_GET_ALL_VALUES:\
case FURNITURE_ROOT_CONTROLPANEL_FURNITURECONTROLLER_GET_ALL_VALUES: \


#define SET_VALUE_CASES \
case FURNITURE_HTTPCONTROL_SET_VALUE:\
case FURNITURE_ROOT_CONTROLPANEL_FURNITURECONTROLLER_SET_VALUE: \
case EN_FURNITURE_FURNITURECONTROLLER_SET_VALUE: \
case EN_FURNITURE_ELECTRIC_FAN_SET_VALUE: \
case EN_FURNITURE_LED_SET_VALUE: \
case EN_FURNITURE_START_SET_VALUE: \
case EN_FURNITURE_STOP_SET_VALUE: \
case EN_FURNITURE_LAMP_SET_VALUE: \
case EN_FURNITURE_LIGHTCONFIRM_SET_VALUE: \
case EN_FURNITURE_CURRENTTEMP_SET_VALUE: \
case EN_FURNITURE_MODESTRINGPROPERTY_SET_VALUE: \
case EN_FURNITURE_CHECKBOXPROPERTY_SET_VALUE: \
case EN_FURNITURE_STARTDATEPROPERTY_SET_VALUE: \
case EN_FURNITURE_STARTTIMEPROPERTY_SET_VALUE: \


#define ACTION_CASES \
case EN_FURNITURE_START_EXEC: \
case EN_FURNITURE_STOP_EXEC: \
case EN_FURNITURE_LAMP_EXEC: \
case EN_FURNITURE_LIGHTCONFIRM_EXEC_ACTION1: \
case EN_FURNITURE_LIGHTCONFIRM_EXEC_ACTION2: \
case EN_FURNITURE_LIGHTCONFIRM_EXEC_ACTION3: \


#define GET_URL_CASES \
case FURNITURE_HTTPCONTROL_GET_ROOT_URL:\


#define CONTROLPANELAPPOBJECTS     {  FurnitureHttpControlObjectPath, HttpControlInterfaces  }, \
	    {  FurnitureFurnitureControllerObjectPath, ControlPanelInterfaces  }, \
	    {  enFurnitureFurnitureControllerObjectPath, ContainerInterfaces  }, \
	    {  enFurnitureElectric_FanObjectPath, PropertyInterfaces  }, \
	    {  enFurnitureLedObjectPath, PropertyInterfaces  }, \
	    {  enFurnitureStartObjectPath, ActionInterfaces  }, \
	    {  enFurnitureStopObjectPath, ActionInterfaces  }, \
	    {  enFurnitureLampObjectPath, ActionInterfaces  }, \
	    {  enFurnitureLightConfirmObjectPath, DialogInterfaces  }, \
	    {  enFurnitureCurrentTempObjectPath, LabelPropertyInterfaces  }, \
	    {  enFurnitureModeStringPropertyObjectPath, PropertyInterfaces  }, \
	    {  enFurnitureCheckboxPropertyObjectPath, PropertyInterfaces  }, \
	    {  enFurnitureStartDatePropertyObjectPath, PropertyInterfaces  }, \
	    {  enFurnitureStartTimePropertyObjectPath, PropertyInterfaces  }, \


#define CONTROLPANELANNOUNCEOBJECTS     {  FurnitureHttpControlObjectPath, HttpControlInterfaces  }, \
	    {  FurnitureFurnitureControllerObjectPath, ControlPanelInterfaces  }, \


#define MAX_NUM_LANGUAGES 1

#define NUM_CONTROLPANEL_OBJECTS 14

#define FURNITURE_MYLANGUAGES_EN 0

#define FURNITURE_HTTPCONTROL_GET_VALUE             AJ_APP_MESSAGE_ID(0 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define FURNITURE_HTTPCONTROL_SET_VALUE             AJ_APP_MESSAGE_ID(0 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define FURNITURE_HTTPCONTROL_GET_ALL_VALUES        AJ_APP_MESSAGE_ID(0 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define FURNITURE_HTTPCONTROL_VERSION_PROPERTY      AJ_APP_PROPERTY_ID(0 + NUM_PRECEDING_OBJECTS, 1, 0)
#define FURNITURE_HTTPCONTROL_GET_ROOT_URL          AJ_APP_MESSAGE_ID(0 + NUM_PRECEDING_OBJECTS, 1, 1)

#define FURNITURE_ROOT_CONTROLPANEL_FURNITURECONTROLLER_GET_VALUE                  AJ_APP_MESSAGE_ID(1 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define FURNITURE_ROOT_CONTROLPANEL_FURNITURECONTROLLER_SET_VALUE                  AJ_APP_MESSAGE_ID(1 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define FURNITURE_ROOT_CONTROLPANEL_FURNITURECONTROLLER_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(1 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define FURNITURE_ROOT_CONTROLPANEL_FURNITURECONTROLLER_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(1 + NUM_PRECEDING_OBJECTS, 1, 0)

#define EN_FURNITURE_FURNITURECONTROLLER_GET_VALUE                  AJ_APP_MESSAGE_ID(2 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define EN_FURNITURE_FURNITURECONTROLLER_SET_VALUE                  AJ_APP_MESSAGE_ID(2 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define EN_FURNITURE_FURNITURECONTROLLER_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(2 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define EN_FURNITURE_FURNITURECONTROLLER_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(2 + NUM_PRECEDING_OBJECTS, 1, 0)
#define EN_FURNITURE_FURNITURECONTROLLER_STATES_PROPERTY            AJ_APP_PROPERTY_ID(2 + NUM_PRECEDING_OBJECTS, 1, 1)
#define EN_FURNITURE_FURNITURECONTROLLER_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(2 + NUM_PRECEDING_OBJECTS, 1, 2)
#define EN_FURNITURE_FURNITURECONTROLLER_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(2 + NUM_PRECEDING_OBJECTS, 1, 3)

#define EN_FURNITURE_ELECTRIC_FAN_GET_VALUE                  AJ_APP_MESSAGE_ID(3 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define EN_FURNITURE_ELECTRIC_FAN_SET_VALUE                  AJ_APP_MESSAGE_ID(3 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define EN_FURNITURE_ELECTRIC_FAN_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(3 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define EN_FURNITURE_ELECTRIC_FAN_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(3 + NUM_PRECEDING_OBJECTS, 1, 0)
#define EN_FURNITURE_ELECTRIC_FAN_STATES_PROPERTY            AJ_APP_PROPERTY_ID(3 + NUM_PRECEDING_OBJECTS, 1, 1)
#define EN_FURNITURE_ELECTRIC_FAN_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(3 + NUM_PRECEDING_OBJECTS, 1, 2)
#define EN_FURNITURE_ELECTRIC_FAN_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(3 + NUM_PRECEDING_OBJECTS, 1, 3)
#define EN_FURNITURE_ELECTRIC_FAN_VALUE_PROPERTY             AJ_APP_PROPERTY_ID(3 + NUM_PRECEDING_OBJECTS, 1, 4)
#define EN_FURNITURE_ELECTRIC_FAN_SIGNAL_VALUE_CHANGED       AJ_APP_MESSAGE_ID(3 + NUM_PRECEDING_OBJECTS, 1, 5)

#define EN_FURNITURE_LED_GET_VALUE                  AJ_APP_MESSAGE_ID(4 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define EN_FURNITURE_LED_SET_VALUE                  AJ_APP_MESSAGE_ID(4 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define EN_FURNITURE_LED_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(4 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define EN_FURNITURE_LED_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(4 + NUM_PRECEDING_OBJECTS, 1, 0)
#define EN_FURNITURE_LED_STATES_PROPERTY            AJ_APP_PROPERTY_ID(4 + NUM_PRECEDING_OBJECTS, 1, 1)
#define EN_FURNITURE_LED_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(4 + NUM_PRECEDING_OBJECTS, 1, 2)
#define EN_FURNITURE_LED_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(4 + NUM_PRECEDING_OBJECTS, 1, 3)
#define EN_FURNITURE_LED_VALUE_PROPERTY             AJ_APP_PROPERTY_ID(4 + NUM_PRECEDING_OBJECTS, 1, 4)
#define EN_FURNITURE_LED_SIGNAL_VALUE_CHANGED       AJ_APP_MESSAGE_ID(4 + NUM_PRECEDING_OBJECTS, 1, 5)

#define EN_FURNITURE_START_GET_VALUE                  AJ_APP_MESSAGE_ID(5 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define EN_FURNITURE_START_SET_VALUE                  AJ_APP_MESSAGE_ID(5 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define EN_FURNITURE_START_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(5 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define EN_FURNITURE_START_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(5 + NUM_PRECEDING_OBJECTS, 1, 0)
#define EN_FURNITURE_START_STATES_PROPERTY            AJ_APP_PROPERTY_ID(5 + NUM_PRECEDING_OBJECTS, 1, 1)
#define EN_FURNITURE_START_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(5 + NUM_PRECEDING_OBJECTS, 1, 2)
#define EN_FURNITURE_START_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(5 + NUM_PRECEDING_OBJECTS, 1, 3)
#define EN_FURNITURE_START_EXEC                       AJ_APP_MESSAGE_ID(5 + NUM_PRECEDING_OBJECTS, 1, 4)

#define EN_FURNITURE_STOP_GET_VALUE                  AJ_APP_MESSAGE_ID(6 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define EN_FURNITURE_STOP_SET_VALUE                  AJ_APP_MESSAGE_ID(6 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define EN_FURNITURE_STOP_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(6 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define EN_FURNITURE_STOP_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(6 + NUM_PRECEDING_OBJECTS, 1, 0)
#define EN_FURNITURE_STOP_STATES_PROPERTY            AJ_APP_PROPERTY_ID(6 + NUM_PRECEDING_OBJECTS, 1, 1)
#define EN_FURNITURE_STOP_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(6 + NUM_PRECEDING_OBJECTS, 1, 2)
#define EN_FURNITURE_STOP_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(6 + NUM_PRECEDING_OBJECTS, 1, 3)
#define EN_FURNITURE_STOP_EXEC                       AJ_APP_MESSAGE_ID(6 + NUM_PRECEDING_OBJECTS, 1, 4)

#define EN_FURNITURE_LAMP_GET_VALUE                  AJ_APP_MESSAGE_ID(7 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define EN_FURNITURE_LAMP_SET_VALUE                  AJ_APP_MESSAGE_ID(7 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define EN_FURNITURE_LAMP_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(7 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define EN_FURNITURE_LAMP_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(7 + NUM_PRECEDING_OBJECTS, 1, 0)
#define EN_FURNITURE_LAMP_STATES_PROPERTY            AJ_APP_PROPERTY_ID(7 + NUM_PRECEDING_OBJECTS, 1, 1)
#define EN_FURNITURE_LAMP_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(7 + NUM_PRECEDING_OBJECTS, 1, 2)
#define EN_FURNITURE_LAMP_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(7 + NUM_PRECEDING_OBJECTS, 1, 3)
#define EN_FURNITURE_LAMP_EXEC                       AJ_APP_MESSAGE_ID(7 + NUM_PRECEDING_OBJECTS, 1, 4)

#define EN_FURNITURE_LIGHTCONFIRM_GET_VALUE                  AJ_APP_MESSAGE_ID(8 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define EN_FURNITURE_LIGHTCONFIRM_SET_VALUE                  AJ_APP_MESSAGE_ID(8 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define EN_FURNITURE_LIGHTCONFIRM_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(8 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define EN_FURNITURE_LIGHTCONFIRM_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(8 + NUM_PRECEDING_OBJECTS, 1, 0)
#define EN_FURNITURE_LIGHTCONFIRM_STATES_PROPERTY            AJ_APP_PROPERTY_ID(8 + NUM_PRECEDING_OBJECTS, 1, 1)
#define EN_FURNITURE_LIGHTCONFIRM_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(8 + NUM_PRECEDING_OBJECTS, 1, 2)
#define EN_FURNITURE_LIGHTCONFIRM_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(8 + NUM_PRECEDING_OBJECTS, 1, 3)
#define EN_FURNITURE_LIGHTCONFIRM_MESSAGE_PROPERTY           AJ_APP_PROPERTY_ID(8 + NUM_PRECEDING_OBJECTS, 1, 4)
#define EN_FURNITURE_LIGHTCONFIRM_NUM_ACTIONS_PROPERTY       AJ_APP_PROPERTY_ID(8 + NUM_PRECEDING_OBJECTS, 1, 5)
#define EN_FURNITURE_LIGHTCONFIRM_EXEC_ACTION1               AJ_APP_MESSAGE_ID(8 + NUM_PRECEDING_OBJECTS, 1, 6)
#define EN_FURNITURE_LIGHTCONFIRM_EXEC_ACTION2               AJ_APP_MESSAGE_ID(8 + NUM_PRECEDING_OBJECTS, 1, 7)
#define EN_FURNITURE_LIGHTCONFIRM_EXEC_ACTION3               AJ_APP_MESSAGE_ID(8 + NUM_PRECEDING_OBJECTS, 1, 8)

#define EN_FURNITURE_CURRENTTEMP_GET_VALUE                  AJ_APP_MESSAGE_ID(9 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define EN_FURNITURE_CURRENTTEMP_SET_VALUE                  AJ_APP_MESSAGE_ID(9 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define EN_FURNITURE_CURRENTTEMP_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(9 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define EN_FURNITURE_CURRENTTEMP_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(9 + NUM_PRECEDING_OBJECTS, 1, 0)
#define EN_FURNITURE_CURRENTTEMP_STATES_PROPERTY            AJ_APP_PROPERTY_ID(9 + NUM_PRECEDING_OBJECTS, 1, 1)
#define EN_FURNITURE_CURRENTTEMP_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(9 + NUM_PRECEDING_OBJECTS, 1, 2)
#define EN_FURNITURE_CURRENTTEMP_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(9 + NUM_PRECEDING_OBJECTS, 1, 3)
#define EN_FURNITURE_CURRENTTEMP_LABEL_PROPERTY             AJ_APP_PROPERTY_ID(9 + NUM_PRECEDING_OBJECTS, 1, 4)

#define EN_FURNITURE_MODESTRINGPROPERTY_GET_VALUE                  AJ_APP_MESSAGE_ID(10 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define EN_FURNITURE_MODESTRINGPROPERTY_SET_VALUE                  AJ_APP_MESSAGE_ID(10 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define EN_FURNITURE_MODESTRINGPROPERTY_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(10 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define EN_FURNITURE_MODESTRINGPROPERTY_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(10 + NUM_PRECEDING_OBJECTS, 1, 0)
#define EN_FURNITURE_MODESTRINGPROPERTY_STATES_PROPERTY            AJ_APP_PROPERTY_ID(10 + NUM_PRECEDING_OBJECTS, 1, 1)
#define EN_FURNITURE_MODESTRINGPROPERTY_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(10 + NUM_PRECEDING_OBJECTS, 1, 2)
#define EN_FURNITURE_MODESTRINGPROPERTY_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(10 + NUM_PRECEDING_OBJECTS, 1, 3)
#define EN_FURNITURE_MODESTRINGPROPERTY_VALUE_PROPERTY             AJ_APP_PROPERTY_ID(10 + NUM_PRECEDING_OBJECTS, 1, 4)
#define EN_FURNITURE_MODESTRINGPROPERTY_SIGNAL_VALUE_CHANGED       AJ_APP_MESSAGE_ID(10 + NUM_PRECEDING_OBJECTS, 1, 5)

#define EN_FURNITURE_CHECKBOXPROPERTY_GET_VALUE                  AJ_APP_MESSAGE_ID(11 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define EN_FURNITURE_CHECKBOXPROPERTY_SET_VALUE                  AJ_APP_MESSAGE_ID(11 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define EN_FURNITURE_CHECKBOXPROPERTY_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(11 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define EN_FURNITURE_CHECKBOXPROPERTY_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(11 + NUM_PRECEDING_OBJECTS, 1, 0)
#define EN_FURNITURE_CHECKBOXPROPERTY_STATES_PROPERTY            AJ_APP_PROPERTY_ID(11 + NUM_PRECEDING_OBJECTS, 1, 1)
#define EN_FURNITURE_CHECKBOXPROPERTY_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(11 + NUM_PRECEDING_OBJECTS, 1, 2)
#define EN_FURNITURE_CHECKBOXPROPERTY_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(11 + NUM_PRECEDING_OBJECTS, 1, 3)
#define EN_FURNITURE_CHECKBOXPROPERTY_VALUE_PROPERTY             AJ_APP_PROPERTY_ID(11 + NUM_PRECEDING_OBJECTS, 1, 4)
#define EN_FURNITURE_CHECKBOXPROPERTY_SIGNAL_VALUE_CHANGED       AJ_APP_MESSAGE_ID(11 + NUM_PRECEDING_OBJECTS, 1, 5)

#define EN_FURNITURE_STARTDATEPROPERTY_GET_VALUE                  AJ_APP_MESSAGE_ID(12 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define EN_FURNITURE_STARTDATEPROPERTY_SET_VALUE                  AJ_APP_MESSAGE_ID(12 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define EN_FURNITURE_STARTDATEPROPERTY_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(12 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define EN_FURNITURE_STARTDATEPROPERTY_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(12 + NUM_PRECEDING_OBJECTS, 1, 0)
#define EN_FURNITURE_STARTDATEPROPERTY_STATES_PROPERTY            AJ_APP_PROPERTY_ID(12 + NUM_PRECEDING_OBJECTS, 1, 1)
#define EN_FURNITURE_STARTDATEPROPERTY_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(12 + NUM_PRECEDING_OBJECTS, 1, 2)
#define EN_FURNITURE_STARTDATEPROPERTY_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(12 + NUM_PRECEDING_OBJECTS, 1, 3)
#define EN_FURNITURE_STARTDATEPROPERTY_VALUE_PROPERTY             AJ_APP_PROPERTY_ID(12 + NUM_PRECEDING_OBJECTS, 1, 4)
#define EN_FURNITURE_STARTDATEPROPERTY_SIGNAL_VALUE_CHANGED       AJ_APP_MESSAGE_ID(12 + NUM_PRECEDING_OBJECTS, 1, 5)

#define EN_FURNITURE_STARTTIMEPROPERTY_GET_VALUE                  AJ_APP_MESSAGE_ID(13 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define EN_FURNITURE_STARTTIMEPROPERTY_SET_VALUE                  AJ_APP_MESSAGE_ID(13 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define EN_FURNITURE_STARTTIMEPROPERTY_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(13 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define EN_FURNITURE_STARTTIMEPROPERTY_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(13 + NUM_PRECEDING_OBJECTS, 1, 0)
#define EN_FURNITURE_STARTTIMEPROPERTY_STATES_PROPERTY            AJ_APP_PROPERTY_ID(13 + NUM_PRECEDING_OBJECTS, 1, 1)
#define EN_FURNITURE_STARTTIMEPROPERTY_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(13 + NUM_PRECEDING_OBJECTS, 1, 2)
#define EN_FURNITURE_STARTTIMEPROPERTY_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(13 + NUM_PRECEDING_OBJECTS, 1, 3)
#define EN_FURNITURE_STARTTIMEPROPERTY_VALUE_PROPERTY             AJ_APP_PROPERTY_ID(13 + NUM_PRECEDING_OBJECTS, 1, 4)
#define EN_FURNITURE_STARTTIMEPROPERTY_SIGNAL_VALUE_CHANGED       AJ_APP_MESSAGE_ID(13 + NUM_PRECEDING_OBJECTS, 1, 5)



extern const char FurnitureHttpControlObjectPath[];
extern const char FurnitureFurnitureControllerObjectPath[];
extern const char enFurnitureFurnitureControllerObjectPath[];
extern const char enFurnitureElectric_FanObjectPath[];
extern const char enFurnitureLedObjectPath[];
extern const char enFurnitureStartObjectPath[];
extern const char enFurnitureStopObjectPath[];
extern const char enFurnitureLampObjectPath[];
extern const char enFurnitureLightConfirmObjectPath[];
extern const char enFurnitureCurrentTempObjectPath[];
extern const char enFurnitureModeStringPropertyObjectPath[];
extern const char enFurnitureCheckboxPropertyObjectPath[];
extern const char enFurnitureStartDatePropertyObjectPath[];
extern const char enFurnitureStartTimePropertyObjectPath[];


extern ContainerWidget FurnitureFurnitureController;
extern PropertyWidget FurnitureElectric_Fan;
extern PropertyWidget FurnitureLed;
extern ActionWidget FurnitureStart;
extern ActionWidget FurnitureStop;
extern ActionWidget FurnitureLamp;
extern DialogWidget FurnitureLightConfirm;
extern LabelWidget FurnitureCurrentTemp;
extern PropertyWidget FurnitureModeStringProperty;
extern PropertyWidget FurnitureCheckboxProperty;
extern PropertyWidget FurnitureStartDateProperty;
extern PropertyWidget FurnitureStartTimeProperty;


typedef struct {
	const char* sender;
	uint16_t numSignals;
	int32_t signals[MAX_NUM_LANGUAGES];
} SetValueContext;

typedef struct {
	uint8_t signalType;
	int32_t signalId;
} Signal;

typedef struct {
	uint16_t numSignals;
	Signal signals[MAX_NUM_LANGUAGES * 2];
} ExecuteActionContext;
/**
*
* @return
*/
void WidgetsInit();

/**
* Set Value of a property.
* @param replyMsg - reply message
* @param propId - id of property being changed
* @param context - setvaluecontext. can be used to send signals
* @return status
*/
AJ_Status SetValueProperty(AJ_Message* replyMsg, uint32_t propId, void* context);

/**
* Execute Action
* @param msg - the msg for the response
* @param msgId - the Action being executed
* @param context - ExecuteActionContext used to send signals as a result of action
* @return status
*/
AJ_Status ExecuteAction(AJ_Message* msg, uint32_t msgId, ExecuteActionContext* context);


/* Defines and functions for Tester App */
typedef struct {
	uint32_t msgId;
	uint16_t numParams;
	uint16_t param[3];
} CPSTest;

#define NUMBER_OF_TESTS //NUM_TESTS_GO_HERE

#define ALL_REPLY_CASES                //ALL_REPLIES_GO_HERE

void TestsInit(CPSTest* testsToRun);

void* IdentifyMsgOrPropId(uint32_t identifier, uint16_t* widgetType, uint16_t* propType, uint16_t* language);
void* IdentifyMsgOrPropIdForSignal(uint32_t identifier, uint8_t* isProperty);
uint8_t IdentifyRootMsgOrPropId(uint32_t identifier);
AJSVC_ServiceStatus GeneratedMessageProcessor(AJ_BusAttachment* bus, AJ_Message* msg, AJ_Status* msgStatus);

#endif /* CONTROL_GENERATED_H_ */
